server:
  port: 8090

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    hikari:
      maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver
    password: price_optimization
    username: price_optimization
    url: jdbc:postgresql://localhost:5433/postgres

axon:
  serializer:
    general: jackson

